### ISSUE TITLE
Login button missing on create account page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal---Liz-Store-dev.---31-May-2022#16]
Bug - Back to login page button mssing on create account page.
Exp - Add login button on create account page.
Ref Link - https://nimb.ws/ghapXY

**Comment by devabulabbas** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Not Fixed - @ui-manjeshyadav Remove login button UI from create account page and Login button should show below create button.
- https://watch.screencastify.com/v/1FdbGkDdINnL3ZQz5bKO

**Comment by ankitcedcoss** [comment]
Bug Fixed
